### ISSUE TITLE
Rule names inconsistent with the standard ESLint ruleset

### ISSUE THREAD

**Issue by remcohaszing** [Gillespie59/eslint-plugin-angular#177]
The standard ESLint ruleset uses hyphens for the rule names. This plugin uses underscores. It might be better to stick to whatever ESLint uses, in order to keep more consistent `.eslintrc` files.

While at the issue of rule naming conventions; each rule uses the `ng_` prefix. In a `.eslintrc` file this results in prefix of `angular/ng_`.

The result this `.eslintrc` snippet:
```yaml
rules:
  - no-extra-semi: 2
  - angular/ng_document_service: 2
```

I propose to use hyphens and remove the `ng_` prefix. The `.eslintrc` snippet would then look like this:
```yaml
rules:
  - no-extra-semi: 2
  - angular/document-service: 2
```

The latter seems cleaner to me.
