### ISSUE TITLE
no-use-before-define and other ESLint rules

### ISSUE THREAD

**Issue by intellix** [Gillespie59/eslint-plugin-angular#97]
So I've installed this and am using the Sublimelinter plugin. My .eslintrc file contains only what it says in the README.md, which is to enable the plugin and I'm getting complaints about things like `no-use-before-define`. 
Are these rules to be included within this plugin? If not; perhaps there should be a sample config containing the others, such as:

```
plugins:
  - angular

rules:
  quotes: 2, "single"
  no-undef: 0
  no-use-before-define: 0
  no-unused-vars: 0
  key-spacing: 0
  no-shadow: 0
  wrap-iife: 0

globals:
	- angular
```

Great stuff, I was looking into JSCS before but this covers so much more :) Thanks
